" ============================================================
" magentic
" 
" URL:https://github.com/mathia4/magentic
" Author: Mitesh Athia
" License: MIT
" Last Change: 2016/12/30 17:58
" ============================================================

let g:airline#themes#magentic#palette = {}

let s:normal1 = [ "#eeeeee", "#5f5fff", 255, 63 ]
let s:normal2 = [ "#2e323a", "#afafff", 236, 147 ]
let s:normal3 = [ "#eeeeee", "#2e323a", 255, 236 ]
let g:airline#themes#magentic#palette.normal = airline#themes#generate_color_map(s:normal1, s:normal2, s:normal3)

let s:insert1 = [ "#2e323a", "#b5e684", 236, 150 ]
let s:insert2 = [ "#2e323a", "#eeffb4", 236, 229 ]
let s:insert3 = [ "#eeeeee", "#2e323a", 255, 236 ]
let g:airline#themes#magentic#palette.insert = airline#themes#generate_color_map(s:insert1, s:insert2, s:insert3)

let s:replace1 = [ "#2e323a", "#ff5faf", 236, 205 ]
let s:replace2 = [ "#2e323a", "#ffc6e3", 236, 224 ]
let s:replace3 = [ "#eeeeee", "#2e323a", 255, 236 ]
let g:airline#themes#magentic#palette.replace = airline#themes#generate_color_map(s:replace1, s:replace2, s:replace3)

let s:visual1 = [ "#2e323a", "#ffd75f", 236, 221 ]
let s:visual2 = [ "#2e323a", "#fff7a2", 236, 229 ]
let s:visual3 = [ "#eeeeee", "#2e323a", 255, 236 ]
let g:airline#themes#magentic#palette.visual = airline#themes#generate_color_map(s:visual1, s:visual2, s:visual3)

let s:inactive1 = [ "#eeeeee", "#2e323a", 255, 236 ]
let s:inactive2 = [ "#eeeeee", "#2e323a", 255, 236 ]
let s:inactive3 = [ "#eeeeee", "#2e323a", 255, 236 ]
let g:airline#themes#magentic#palette.inactive = airline#themes#generate_color_map(s:inactive1, s:inactive2, s:inactive3)


" ===================================
" Generated by Estilo 1.3.3
" https://github.com/jacoborus/estilo
" ===================================
